"""users table

Revision ID: 918be43d298f
Revises: dd29ec78b885
Create Date: 2018-12-05 14:17:58.867715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918be43d298f'
down_revision = 'dd29ec78b885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_vip', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_vip')
    # ### end Alembic commands ###
